There are following changes i) Added the findClassSet function which is called recursively to go down the tree and look for the classnames (instance of ClassName) and then check if they start with the alreadyEnteredText and in that case add it to the Package toReturn.
ii) Added the constructors with the classnames although in some cases I am getting NoClassDefFoundError which I am catching and ignoring.